import { Navbar } from "@/components/global-navbar";
import { Toaster } from "@/components/ui/sonner";
import { GetSession } from "@/lib/auth/utils";
import I18nProvider from "@/providers/i18n-provider";
import SessionWrapper from "@/providers/session-provider";
import NextThemeProvider from "@/providers/theme-provider";
import type { Metadata } from "next";
import type { Session } from "next-auth";
import { CookiesProvider } from "next-client-cookies/server";
import { Geist, Geist_Mono, Noto_Sans_TC } from "next/font/google";
import "./css/globals.css";

const notoSans = Noto_Sans_TC({
	variable: "--font-noto-sans",
	weight: ["600"],
	subsets: ["latin"],
});

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = (await GetSession()) as Session;

	return (
		<SessionWrapper session={session}>
			<html lang="en">
				<body
					className={`${notoSans.variable} ${geistSans.variable} ${geistMono.variable} antialiased dark [--scroll-mt:9.875rem] lg:[--scroll-mt:6.3125rem] [scrollbar-gutter:stable]`}
				>
					<NextThemeProvider
						attribute="class"
						defaultTheme="dark"
						enableSystem
						disableTransitionOnChange
					>
						<CookiesProvider>
							<I18nProvider>{children}</I18nProvider>
						</CookiesProvider>
					</NextThemeProvider>
					<Toaster />
				</body>
			</html>
		</SessionWrapper>
	);
}
